export const PhoneWordsActionTypes = {
  FETCH_PHONEWORDS_START: 'FETCH_PHONEWORDS_START',
  FETCH_PHONEWORDS_SUCCESS: 'FETECH_PHONEWORDS_SUCCESS',
  FETCH_PHONEWORDS_FAILURE: 'FETCH_PHONEWORDS_FAILURE',
  CLEAR_PHONEWORDS: 'CLEAR_PHONEWORDS'
}